Make api_gen visibile in all subpackages of tensorflow.
Python3.5 and Python3.6 have errors while building:

```
ERROR: /tmpfs/src/github/tensorflow/bazel_pip/tensorflow/tools/api/tests/BUILD:16:1: in py_test rule //bazel_pip/tensorflow/tools/api/tests:api_compatibility_test: target '//tensorflow:tf_python_api_gen_v2' is not visible from target '//bazel_pip/tensorflow/tools/api/tests:api_compatibility_test'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

Most likely Bazel default python doesn't properly catch the visibility
declaration, so we're trying to use this fix instead.